config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get "sobre", to: 'pages#sobre', as: :"sobre" #about page
  get "politica-de-privacidade", to: 'pages#politicadeprivacidade', as: :"politica-de-privacidade" #politica-de-privacidade
  get "termos-de-uso", to: 'pages#termosdeuso', as: :"termos-de-uso" #termos-de-uso
  get "obrigado", to: 'pages#obrigado', as: :"muito-obrigado" #termos-de-uso
  get "curriculocampeao", to: 'pages#curriculocampeao', as: :"curriculo-campeao" #bonus 1

  #paginas de lançamentoo

  get "lan-inscricao", to: 'pages#lan_inscricao', as: :"lan-inscricao"
  get "lan-obrigado", to: 'pages#lan_obrigado', as: :"lan-obrigado"
  get "lan-live", to: 'pages#lan_live', as: :"lan-live"
  get "lan-confirmacao", to: 'pages#lan_confirmacao', as: :"lan-confirmacao"

  get "sua-ajuda", to: 'pages#sua_ajuda', as: :"sua-ajuda"

  get "inscricoes-encerradas", to: 'pages#inscricoes_encerradas', as: :"inscricoes-encerradas"


  #cursos
  get "novenovecv", to: 'pages#novenovecv', as: :"novenovecv"
  get "aprovando-em-entrevistas", to: 'pages#aprovando_em_entrevistas', as: :"aprovando-em-entrevistas"
  get "obrigado-waitlist", to: 'pages#obrigado_waitlist', as: :"obrigado-waitlist"

  #portaldevagas
  get "portal-de-vagas", to: 'pages#portal_de_vagas', as: :"portal_de_vagas"
  get "inscricoes-para-portal-encerradas", to: 'pages#inscricoes_para_portal_encerradas', as: :"inscricoes_para_portal_encerradas"

  get "lista-de-vagas", to: 'pages#lista_de_vagas', as: :"lista_de_vagas"

  #blog | dicas de entrevista
  get "dicas-de-entrevista", to: 'pages#dicas_de_entrevista', as: :"dicas-de-entrevista"



#POSTS---------------------------------------------------------------------------------------------

  get "transformacoes-que-atraves-da-beleza-sao-entregues-em-produtos-de-varios-formatos", to: 'blog#post0', as: :"transformacoes-que-atraves-da-beleza-sao-entregues-em-produtos-de-varios-formatos"  #POST 0
  get "o-futuro-do-salao-de-beleza", to: 'blog#post1', as: :"o-futuro-do-salao-de-beleza" #POST 1
  get "quais-os-pilares-de-um-bom-curriculo", to: 'blog#post2', as: :"quais-os-pilares-de-um-bom-curriculo" #POST 2
  get "as-5-perguntas-mais-comuns-em-entrevistas", to: 'blog#post3', as: :"as-5-perguntas-mais-comuns-em-entrevistas" #POST 3
  get "como-falar-sobre-qualidades-e-defeitos-em-uma-entrevista-de-trabalho", to: 'blog#post4', as: :"como-falar-sobre-qualidades-e-defeitos-em-uma-entrevista-de-trabalho" #POST 4
  get "como-escrever-seu-curriculo-sem-ter-experiencias-profissionais", to: 'blog#post5', as: :"como-escrever-seu-curriculo-sem-ter-experiencias-profissionais" #POST 5
  get "como-lidar-com-exigencias-absurdas-de-entrevistas-de-emprego", to: 'blog#post6', as: :"como-lidar-com-exigencias-absurdas-de-entrevistas-de-emprego" #POST 6
  get "como-foi-minha-primeira-entrevista-de-emprego", to: 'blog#post7', as: :"como-foi-minha-primeira-entrevista-de-emprego" #POST 7


#VAGAS---------------------------------------------------------------------------------------------

  get "vaga-598", to: 'vagas#vaga0', as: :"vaga1"  #vaga100 - 0
  get "vaga-333", to: 'vagas#vaga1', as: :"vaga2"  #vaga100 - 1
  get "vaga-294", to: 'vagas#vaga2', as: :"vaga3"  #vaga100 - 2
  get "vaga-128", to: 'vagas#vaga3', as: :"vaga4"  #vaga100 - 3
  get "vaga-403", to: 'vagas#vaga4', as: :"vaga5"  #vaga100 - 4
  get "vaga-733", to: 'vagas#vaga5', as: :"vaga6"  #vaga100 - 5




end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  skip_before_action :authenticate_user!


  def post0
    @post = posts_all[0]
  end

  def post1
    @post = posts_all[1]
  end

  def post2
    @post = posts_all[2]
  end

  def post3
     @post = posts_all[3]
  end

  def post4
     @post = posts_all[4]
  end

  def post5
     @post = posts_all[5]
  end

  def post6
     @post = posts_all[6]
  end

  def post7
     @post = posts_all[7]
  end




private

def posts_all
  postsYAML = YAML.load(ERB.new(File.read("config/post.yml")).result(binding))
  posts_all = postsYAML.collect { |k, v| v }
  #posts_all = posts_all.reverse
end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @posts = posts_all.to_h
    #@firstpost = @posts["ultimo"]
    @secondposts = @posts

    @vagas = vagas_all.to_h
      @vaga1 = @vagas["vaga0"]
      @vaga2 = @vagas["vaga1"]
      @vaga3 = @vagas["vaga2"]
  end

  def sobre
  end

  def obrigado
    redirect_to(root_path)
  end

  def curriculocampeao
    redirect_to(root_path)
  end

  def termosdeuso
    redirect_to(root_path)
  end

  def politicadeprivacidade
    redirect_to(root_path)
  end

  def lan_inscricao
    #redirect_to(root_path)
  end

  def lan_obrigado
    #redirect_to(root_path)
  end

  def lan_live
    redirect_to(root_path)
    #https://pay.hotmart.com/thanks?bid=1582468627395
  end

  def lan_confirmacao
    #redirect_to(root_path)
  end

  def sua_ajuda
    redirect_to(root_path)
    #redirect_to(lan_inscricao_path)
  end

  def inscricoes_encerradas

  end

  #PORTAL DE VAGAS
  def portal_de_vagas
    redirect_to(root_path)
    @position = rand(100..1000)
    @type = ["Trainee", "Analista", "Coordenador", "Gerente", "Estágio"]
    @local = ["Empresa nacional", "Empresa multinacional"]
    @area = ["Tecnologia", "Vendas", "Logística", "Varejo", "Finanças", "Investimentos", "Abastecimento"]

    @vagas = vagas_all.to_h
      @vaga1 = @vagas["vaga0"]
      @vaga2 = @vagas["vaga1"]
      @vaga3 = @vagas["vaga2"]
  end

  #LISTA DE VAGAS
  def lista_de_vagas
    redirect_to(root_path)

  end


  def inscricoes_para_portal_encerradas
    redirect_to(root_path)

  end


#Cursos

  def novenovecv
    redirect_to(inscricoes_encerradas_path)
  end

  def aprovando_em_entrevistas
    redirect_to(inscricoes_encerradas_path)
  end

  def obrigado_waitlist
    redirect_to(inscricoes_encerradas_path)
  end


#blog | dicas de entrevista

def dicas_de_entrevista
  @posts = posts_all.to_h
  #@firstpost = @posts["ultimo"]
  @secondposts = @posts

end



  private

    def posts_all
      file = "config/post.yml"
      posts_all = YAML.load(open(file).read)
      posts_all = posts_all.reverse_each.to_h
    end

    def vagas_all
      file_vagas = "config/vagas.yml"
      vagas_all = YAML.load(open(file_vagas).read)
      vagas_all = vagas_all.to_h
      #vagasYAML = YAML.load(ERB.new(File.read("config/vagas.yml")).result(binding))
      #vagas_all = vagasYAML.collect { |k, v| v }
      #posts_all = posts_all.reverse
    end

end

app/controllers/vagas_controller.rb
class VagasController < ApplicationController
  skip_before_action :authenticate_user!


  def vaga0
    @vaga = vagas_all[0]
  end

  def vaga1
    @vaga = vagas_all[1]
  end

  def vaga2
    @vaga = vagas_all[2]
  end

  def vaga3
     @vaga = vagas_all[3]
  end

  def vaga4
     @vaga = vagas_all[4]
  end

  def vaga5
     @vaga = vagas_all[5]
  end




private

def vagas_all
  vagasYAML = YAML.load(ERB.new(File.read("config/vagas.yml")).result(binding))
  vagas_all = vagasYAML.collect { |k, v| v }
  #posts_all = posts_all.reverse
end



end

app/views/blog/post0.html.erb
<%= render 'shared/post' %>

app/views/blog/post1.html.erb
<%= render 'shared/post' %>

app/views/blog/post2.html.erb
<%= render 'shared/post' %>

app/views/blog/post3.html.erb
<%= render 'shared/post' %>

app/views/blog/post4.html.erb
<%= render 'shared/post' %>

app/views/blog/post5.html.erb
<%= render 'shared/post' %>

app/views/blog/post6.html.erb
<%= render 'shared/post' %>

app/views/blog/post7.html.erb
<%= render 'shared/post' %>

app/views/pages/obrigado.html.erb
<style>
.videoContainer {
background: #373B44;  /* fallback for old browsers */
background: -webkit-linear-gradient(to right, #9a1278, #003fff);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to right, #9a1278, #003fff); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

  width: 100%;
  height: 80vh;

  overflow: hidden;
  margin-top: 0px;
}

#videoTrailer {
  min-width: 100%;
  max-height: 100%;
  vertical-align: middle;
}

.title-text {
  color: white;
  font-size: 3.5vh;
  padding: 0.5vh;

  display:inline-block;
  padding-left: 1.5vh;
  padding-right: 1.5vh;

}

.btn-text {
  color: white;
  background-color: #F0386B;
  margin: 20px;
  font-size: 2.5vh;

}

.zoom:hover {
  transform: scale(1.02);
}

.link-style-obrigado {

  color: black;
  font-size: 5vh;
  padding: 2vh;
  margin-top: 0vh;
}

.img-size-logo {
  max-height: 120px;
}

.divborder {
  border-style: solid;
  border-width: thin;
  border-color: white;
  margin: 4px;
  color: white;
  display: inline-block;
  border-radius: 3px;
}

.divborder:hover {
  background-color: black;
  border-color: black;
}

.textdivborder {
  margin: 0 auto;
  padding: 2px;
  margin-left: 20px;
  margin-right: 20px;
}

</style>


<div class="videoContainer">
  <img id="videoTrailer" style="object-fit: cover; height: 80vh; opacity: 1;" src="/assets/background2.gif" alt="sobre/about">
  <div style="position: relative; margin-top: -75vh;">
    <div class="container">
    <center>
    <%= image_tag "logofim.png", class: 'img-responsive center-block fit-image img-size-logo' , alt: "Entrevista Descomplicada" %>
    <h1 class="title-text" style="margin-top: 1vh;">Muito Obrigado</h1>
    <p class="" style="font-size: 2.5vh; margin-left: 0.2vh; margin-right: 0.2vh; color: white;">Verifique seu email pra baixar o modelo de currículo!
    <p class="" style="font-size: 1.5vh; margin-left: 0.2vh; margin-right: 0.2vh; color: white;">Grande abraço <br> Zé Ricardo | Co-fundador da Entrevista Descomplicada </p>
    </center>

      <br>
      <div class="container">
        <p style="color: white; margin-bottom: 0vh; font-size: 2vh; font-style: italic;">Veja também:</p>

        <%= link_to inscricoes_encerradas_path do %>
          <div class="divborder" >
          <p class="textdivborder"><i class="fas fa-book-open"></i>        CURSOS PREPARATÓRIOS</p>
          </div>
          <br>
        <% end %>

        <%= link_to portal_de_vagas_path do %>
        <div class="divborder">
        <p class="textdivborder"><i class="fas fa-laptop"></i>        PORTAL DE VAGAS</p>
        </div>
        <br>
        <% end %>

        <%= link_to dicas_de_entrevista_path do %>
        <div class="divborder">
        <p class="textdivborder"><i class="fas fa-wrench"></i>        DICAS DE ENTREVISTA</p>
        </div>
        <% end %>
      </div>

    </div>

  </div>
</div>



<%= render 'shared/perfilsocial' %>

<%= render 'shared/depoimentos' %>

<%= render 'shared/quemsomos' %>



</div>

app/views/pages/obrigado_waitlist.html.erb
<style>
.videoContainer {
  background: #373B44;  /* fallback for old browsers */
  background: -webkit-linear-gradient(to right, #9a1278, #003fff);  /* Chrome 10-25, Safari 5.1-6 */
  background: linear-gradient(to right, #9a1278, #003fff); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

  width: 100%;
  height: 70vh;

  overflow: hidden;
  margin-top: 0px;
}

#videoTrailer {
  min-width: 100%;
  max-height: 100%;
  vertical-align: middle;
  object-fit: cover;
  height: 70vh;
  opacity: 1;
}

.title-text {
  color: white;
  font-size: 3.5vh;
  padding: 0.5vh;
  display:inline-block;
  padding-left: 1.5vh;
  padding-right: 1.5vh;
  margin-top: 1vh;

}

.paragraph-text {
  margin-left: 0.2vh;
  margin-right: 0.2vh;
  color: white;
}

.seealso {
  color: white;
  margin-bottom: 0vh;
  font-size: 2vh;
  font-style: italic;
}



.btn-text {
  color: white;
  background-color: #F0386B;
  margin: 20px;
  font-size: 2.5vh;

}

.zoom:hover {
  transform: scale(1.02);
}

.link-style-obrigado {

  color: black;
  font-size: 5vh;
  padding: 2vh;
  margin-top: 0vh;
}

.img-size-logo {
  max-height: 120px;
}

.divborder {
  border-style: solid;
  border-width: thin;
  border-color: white;
  margin: 4px;
  color: white;
  display: inline-block;
  border-radius: 3px;
}

.divborder:hover {
  background-color: black;
  border-color: black;
}

.textdivborder {
  margin: 0 auto;
  padding: 2px;
  margin-left: 20px;
  margin-right: 20px;
}

</style>


<div class="videoContainer">
  <img id="videoTrailer" src="/assets/background2.gif" alt="sobre/about">
  <div style="position: relative; margin-top: -65vh;">
    <div class="container">
      <center>
        <%= image_tag "logofim.png", class: 'img-responsive center-block fit-image img-size-logo' , alt: "Entrevista Descomplicada" %>
        <h1 class="title-text">Email recebido</h1>
        <p class="paragraph-text" style="font-size: 2.5vh;">Assim que abrirmos a nova turma dos nossos cursos te avisaremos!! :)
        <p class="paragraph-text" style="font-size: 1.5vh;">Grande abraço <br> Zé Ricardo | Co-fundador da Entrevista Descomplicada </p>
      </center>
      <br>

      <div class="container">
        <p class="seealso" >Enquanto isso veja também:</p>
        <%= link_to portal_de_vagas_path do %>
          <div class="divborder">
          <p class="textdivborder"><i class="fas fa-laptop"></i>        PORTAL DE VAGAS</p>
          </div>
          <br>
        <% end %>
        <%= link_to dicas_de_entrevista_path do %>
          <div class="divborder">
          <p class="textdivborder"><i class="fas fa-wrench"></i>        DICAS DE ENTREVISTA</p>
          </div>
          <br>
        <% end %>
      </div>
    </div>
  </div>
</div>


<%= render 'shared/perfilsocial' %>

<%= render 'shared/depoimentos' %>

<%= render 'shared/quemsomos' %>


</div>

app/views/shared/_cursos.html.erb
<!-- SESSAO CURSOS ***************** -->
<div style="background-color: black; padding: 3vh; z-index: 10; position:relative; color: gray;">
  <div class="container">
  <h2 style="color: gray;">Conheça nossos cursos:</h2>
  <br>
  <div class="row">
    <div class="col-xs-12 col-sm-6 zoom">
      <center>
        <div style="margin-bottom: 3vh;">
          <%= image_tag "99CV.png", class: 'img-responsive center-block fit-image-courses', alt: "Curso preparatório para entrevista 99CV" %> <br>
          <p style="font-size: 2vh;">Curso 100% focado no desenvolvimento o currículo do candidato, a porta de entrada em todo processo seletivo para vagas de estágio, trainee ou trabalho</p>
          <%= link_to inscricoes_encerradas_path do %> <!-- novenovecv_path  -->
            <div class="btn btn-text" style="margin-top: -0.3vh;">Saiba mais</div>
          <% end %>
        </div>

      </center>
    </div>

    <div class="col-xs-12 col-sm-6 zoom">
      <center>
        <div style="margin-bottom: 3vh;">
          <%= image_tag "AE2.png", class: 'img-responsive center-block fit-image-courses', alt: "Curso preparatório para entrevista 99CV" %> <br>
          <p style="font-size: 2vh;">Curso dedicado a ensinar o candidado a fazer a entrevista de emprego de modo excepcional, de forma a ser aprovado em todas as etapas do processo seletivo e conseguir a vaga de trabalho</p>
          <%= link_to inscricoes_encerradas_path do %> <!-- aprovando_em_entrevistas_path -->
            <div class="btn btn-text" style="margin-top: -0.3vh;">Saiba mais</div>
          <% end %>
        </div>
      </center>
    </div>
  </div>
  </div>
</div>
<br>
<br>
<!-- SESSAO CURSOS ***************** -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_garantia.html.erb
<!-- SEÇÃO GARANTIA 30 DIAS-->
<center>
  <br>
  <div class="container">
    <br>
    <%= image_tag "garantia.png", class: 'img-responsive center-block fit-image-garantia', alt: "Entrevista Descomplicada - Curso 99CV" %>

    <h3>VOCÊ NÃO TEM NADA À PERDER...</h3>
    <h4 style="font-weight: 300; color: grey; line-height: 1.5; font-size: 2.5vh; padding: 2vh;">Não existe dúvida, o curso 99CV funciona, a prova disso são os muitos alunos com resultados em diversos processos seletivos. Mas se você ainda tem alguma dúvida você pode experimentar por 7 dias e, caso você não goste ou não veja nenhum resultado, basta enviar um email durante esse período que todo o valor investido será 100% reembolsado.
    <br>
    <br>
    Ou seja, se der certo você será convidado(a) para entrevista que desejar, se der errado você tem 100% do seu dinheiro de volta.
    <br>
    <br>
    <strong>O único risco que você corre é continuar procurando emprego sem resultados efetivos. Simples assim!</strong></h4>
    <%= link_to novenovecv_path do %>
      <div class="btn btn-danger btn-text-curso">QUERO RESULTADOS EFETIVOS</div>
      <p style="color: black;">Link para inscrição</p>
    <% end %>
    <br>
  </div>
</center>
<!-- FIM SEÇÃO GARANTIA 30 DIAS-->

app/views/shared/_navbar.html.erb
<style>
.navbar-wagon {
  box-shadow: 0 1px 5px 0 rgba(0,0,0,0.07),0 1px 0 0 rgba(0,0,0,0.03);
  background: white;
  transition: all 0.3s ease;
  height: 45px;
  padding: 0px 30px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  z-index: 1;
}

/* Logo */
.navbar-wagon-brand img {
  height: 35px;
}

/* User Avatar */
.navbar-wagon .avatar {
  height: 35px;
  width: 35px;
  border-radius: 50%;
}

/* Right section */
.navbar-wagon-right {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

/* Basic navbar item */
.navbar-wagon-item {
  cursor: pointer;
  padding: 0 0px;
}

.navbar-wagon-item-cidade {
  cursor: pointer;
  padding: 0 20px;
}

/* Navbar link */
.navbar-wagon-link {
  color: #6E6E6E;
  font-size: 14px;
}
.navbar-wagon-link:hover {
  color: #da552f;
  text-decoration: none;
}

.navbar-wagon-link-btn {
  color: white;
  font-size: 14px;
  padding: 3px;
}
.navbar-wagon-link-btn:hover {
  color: white;
  text-decoration: none;
}



/* Dropdown menu */
.navbar-wagon-dropdown-menu {
  margin-top: 15px;
  box-shadow: 1px 1px 4px #E6E6E6;
  border-color: #E6E6E6;
}
.navbar-wagon-dropdown-menu li > a {
  transition: color 0.3s ease;
  font-weight: lighter !important;
  color: #6E6E6E !important;
  font-size: 15px !important;
  line-height: 22px !important;
  padding: 10px 20px;
}
.navbar-wagon-dropdown-menu li > a:hover {
  background: transparent !important;
  color: black !important;
}
.navbar-wagon-dropdown-menu:before {
  content: ' ';
  height: 10px;
  width: 10px;
  position: absolute;
  right: 10px;
  top: -6px;
  background-color: white;
  transform: rotate(45deg);
  border-left: 1px solid #E6E6E6;
  border-top: 1px solid #E6E6E6;
}

.nav-logo {
  font-size: 2.5vh;
  background-color: #F0386B;
  object-position: center;
  padding: 5px;
  color: white;
  font-family: 'Barriecito', cursive;
  margin-left: 0px;
  margin-top: 10px;
}


.btn-text-title {
  color: white;
  background-color: #F0386B;
  margin: 0px;
  margin-left: -20px;
  font-size: 2.5vh;
  font-family: 'Barriecito', cursive;
}

.icon-style-navbar {
font-size: 3vh;
padding: 2vh;
color: gray;

}

</style>




<div class="navbar-wagon">
  <!-- Logo -->

  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "https://salaodebelezadelivery.com.br//franquias/2/21698/editor-html/4213895.png", height: 30 %>
  <% end %>

  <!-- Right Navigation -->

<div class="">  <!-- div para hide de menu bar -->

  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <a href="https://www.youtube.com/channel/UCSJlrT44ZLIM77Z6oGIGr3Q" target="_blank"><i class="fab fa-youtube-square icon-style-navbar"></i></a>
    <a href="https://www.facebook.com/salaodebelezadelivery.com.br" target="_blank"><i class="fab fa-facebook-square icon-style-navbar"></i></a>
    <a href="https://www.instagram.com/thiellefelix/" target="_blank"><i class="fab fa-instagram  icon-style-navbar"></i></a>
    <a href="https://twitter.com/thiellefelix" target="_blank"><i class="fab fa-twitter icon-style-navbar"></i></a>
    <a href="https://br.linkedin.com/in/thielle" target="_blank"><i class="fab fa-linkedin icon-style-navbar"></i></a>
    <%= link_to "Blog", root_path, class: "navbar-wagon-item-cidade navbar-wagon-link" %>
    <%#= link_to "Vídeos", root_path, class: "navbar-wagon-item-cidade navbar-wagon-link" %>
    <%#= link_to "Portal de vagas", portal_de_vagas_path, class: "navbar-wagon-item-cidade navbar-wagon-link" %>
    <%#= link_to "Recursos", curriculo_campeao_path, class: "navbar-wagon-item-cidade navbar-wagon-link" %>
    <%#= link_to "Contato", root_path, class: "navbar-wagon-item-cidade navbar-wagon-link hide" %>
    <%= link_to "Sobre", sobre_path, class: "navbar-wagon-item-cidade navbar-wagon-link" %>
    <% if user_signed_in? %>
      <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fas fa-user-check"></i>  <%= t(".sign_out", default: "Sair") %>
      <% end %>
    <% end %>

  </div>



  <div class="navbar-wagon-right hidden-md hidden-lg">

   <!-- Dropdown list appearing on mobile only -->
  <div class="hidden-md hidden-lg">
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <i class="fa fa-bars" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li class="hide">
              <%= link_to root_path do %>
                <i class="fa fa-bullhorn"></i>  <%= t(".settings", default: "Blog") %>
              <% end %>
            </li>
            <li class="hide">
              <%= link_to root_path do %>
                <i class="fa fa-bullhorn"></i>  <%= t(".settings", default: "Vídeos") %>
              <% end %>
            </li>
            <li>
              <%= link_to portal_de_vagas_path do %>
                <i class="fa fa-bullhorn"></i>  <%= t(".settings", default: "Portal de vagas") %>
              <% end %>
            </li>
            <li>
              <%= link_to curriculo_campeao_path do %>
                <i class="fa fa-bullhorn"></i>  <%= t(".settings", default: "Recursos") %>
              <% end %>
            </li>
            <li class="hide">
              <%= link_to root_path do %>
                <i class="fa fa-bullhorn"></i>  <%= t(".settings", default: "Contato") %>
              <% end %>
            </li>
            <li>
              <%= link_to sobre_path do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Sobre") %>
              <% end %>
            </li>
            <li>
              <%= link_to "https://www.youtube.com/channel/UCSJlrT44ZLIM77Z6oGIGr3Q" do %>
                <i class="fab fa-youtube-square"></i>  <%= t(".settings", default: "YouTube") %>
              <% end %>
            </li>
            <li>
              <%= link_to "https://www.facebook.com/salaodebelezadelivery.com.br" do %>
                <i class="fab fa-facebook-square"></i>  <%= t(".settings", default: "Facebook") %>
              <% end %>
            </li>
            <li>
              <%= link_to "https://www.instagram.com/thiellefelix/" do %>
                <i class="fab fa-instagram "></i>  <%= t(".settings", default: "Instagram") %>
              <% end %>
            </li>
            <li>
              <%= link_to "https://br.linkedin.com/in/thielle" do %>
                <i class="fab fa-linkedin "></i>  <%= t(".settings", default: "LinkedIn") %>
              <% end %>
            </li>
            <li>
              <%= link_to "https://twitter.com/thiellefelix" do %>
                <i class="fab fa-twitter "></i>  <%= t(".settings", default: "Twitter") %>
              <% end %>
            </li>
            <% if user_signed_in? %>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-user-check"></i>  <%= t(".sign_out", default: "Sair") %>
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
  </div>

</div>

</div> <!-- div para hide de menu bar -->

</div>

app/views/vagas/vaga0.html.erb
<%= render 'shared/vagas' %>